CREATE TABLE Student (
    student_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    date_of_birth DATE NOT NULL,
    gender VARCHAR2(10),
    address VARCHAR2(100),
    phone_number VARCHAR2(15),
    email VARCHAR2(50)
);

CREATE TABLE Teacher (
    teacher_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    subject VARCHAR2(50),
    phone_number VARCHAR2(15),
    email VARCHAR2(50)
);

CREATE TABLE Class (
    class_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_name VARCHAR2(50) NOT NULL,
    teacher_id NUMBER,
    schedule VARCHAR2(50),
    CONSTRAINT fk_teacher
        FOREIGN KEY (teacher_id) 
        REFERENCES Teacher(teacher_id)
);

CREATE TABLE Enrollment (
    enrollment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id NUMBER,
    class_id NUMBER,
    enrollment_date DATE NOT NULL,
    CONSTRAINT fk_student
        FOREIGN KEY (student_id) 
        REFERENCES Student(student_id),
    CONSTRAINT fk_class
        FOREIGN KEY (class_id) 
        REFERENCES Class(class_id)
);





